version: "3.8"
networks:
  mqttnet:

services:

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    
    ports:
      - "1883:1883"  # MQTT port
      - "9001:9001"  # WebSocket port
    networks:
      - mqttnet

  web:
    build: ./web
    ports:
      - "5000:5000"
    depends_on:
      - mosquitto
    networks:
      - mqttnet

  simulator:
    build: ./broker
    depends_on:
      - mosquitto
    networks:
        - mqttnet



#  simulator:
#    image: eclipse-mosquitto:2.0
#    container_name: mqtt-simulator
#    depends_on:
#      - mosquitto
#    command: >
 #     sh -c "while true; do
  ##   done"
    #networks:
     # - mqttnet